// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-northeast-2',
  aws_cognito_identity_pool_id:
    'ap-northeast-2:374e8889-07b3-4a11-babd-84ee8ed1125e',
  aws_cognito_region: 'ap-northeast-2',
  aws_user_pools_id: 'ap-northeast-2_CttwXaHae',
  aws_user_pools_web_client_id: '65ttv9lht9d389glb3mq9cj8tc'
};

export default awsmobile;
